/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-muted': 'rgb(var(--surface-muted) / <alpha-value>)',
        'surface-strong': 'rgb(var(--surface-strong) / <alpha-value>)',
        ink: 'rgb(var(--ink) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        line: 'var(--line)',
        'line-strong': 'var(--line-strong)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-soft': 'var(--accent-soft)',
        'accent-soft-strong': 'var(--accent-soft-strong)',
        'accent-ink': 'rgb(var(--accent-ink) / <alpha-value>)',
        good: 'rgb(var(--good) / <alpha-value>)',
        warn: 'rgb(var(--warn) / <alpha-value>)',
        'warn-soft': 'var(--warn-soft)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        'danger-soft': 'var(--danger-soft)',
        info: 'rgb(var(--info) / <alpha-value>)',
        'info-soft': 'var(--info-soft)',
        overlay: 'rgb(var(--overlay) / <alpha-value>)',
        sidebar: 'rgb(var(--sidebar-bg) / <alpha-value>)',
        'sidebar-muted-bg': 'rgb(var(--sidebar-surface-muted) / <alpha-value>)',
        'sidebar-ink': 'rgb(var(--sidebar-ink) / <alpha-value>)',
        'sidebar-muted': 'rgb(var(--sidebar-muted) / <alpha-value>)',
        'sidebar-line': 'var(--sidebar-line)',
      },
      boxShadow: {
        soft: '0 10px 40px rgba(17, 17, 17, 0.12)',
      },
    },
  },
  plugins: [],
};
