require('dotenv').config();
const test = require('node:test');
const assert = require('assert');
const { spawn } = require('child_process');
const path = require('path');

const PORT = 3098;
const BASE_URL = `http://localhost:${PORT}`;

test.describe('Prioritized Retrieval (Legislation max 3-4 + Other Tables max 5)', () => {
  let serverProcess;

  test.before(() => {
    return new Promise((resolve, reject) => {
      console.log('Starting backend server for prioritized retrieval tests on port', PORT);
      serverProcess = spawn('node', [path.resolve(__dirname, '../index.js')], {
        cwd: path.resolve(__dirname, '..'),
        env: { ...process.env, PORT: PORT }
      });

      let started = false;

      serverProcess.stdout.on('data', (data) => {
        const output = data.toString();
        if (output.includes(`Server running on port ${PORT}`) || output.includes('listening')) {
          if (!started) {
            started = true;
            resolve();
          }
        }
      });

      serverProcess.stderr.on('data', (data) => {
        const errStr = data.toString();
        if (!errStr.includes('DeprecationWarning')) {
          console.error('[Server Stderr]:', errStr.trim());
        }
      });

      serverProcess.on('error', (err) => {
        reject(err);
      });

      setTimeout(() => {
        if (!started) {
          started = true;
          resolve();
        }
      }, 15000);
    });
  });

  test.after(() => {
    if (serverProcess) {
      console.log('Stopping test backend server');
      serverProcess.kill('SIGINT');
    }
  });

  test('Python search_documents.py negative filter (!Legislation)', async () => {
    const pythonPath = path.resolve(__dirname, '../../embedding/venv/Scripts/python.exe');
    const scriptPath = path.resolve(__dirname, '../../embedding/search_documents.py');

    if (!require('fs').existsSync(pythonPath) || !require('fs').existsSync(scriptPath)) {
      console.log('Python environment or script not found at standard path, skipping raw Python process test');
      return;
    }

    const child = spawn(pythonPath, [scriptPath, '--json']);

    let stdout = '';
    child.stdout.on('data', (data) => { stdout += data.toString(); });

    const inputPayload = JSON.stringify({
      query: 'Corporate Social Responsibility CSR Section 135 Companies Act',
      top_k: 5,
      hybrid: true,
      source_filter: '!Legislation'
    });

    child.stdin.write(inputPayload);
    child.stdin.end();

    await new Promise((resolve) => child.on('close', resolve));

    const parsed = JSON.parse(stdout);
    assert.ok(Array.isArray(parsed.results), 'results should be an array');
    
    // Ensure no result has source_table == 'Legislation'
    for (const item of parsed.results) {
      assert.notStrictEqual(item.source_table, 'Legislation', 'Negative filter should exclude Legislation');
    }
    console.log(`Successfully verified negative source_filter (!Legislation): returned ${parsed.results.length} non-legislation items.`);
  });

  test('POST /api/ask - Prioritized retrieval (Legislation + Other tables context & answer)', async () => {
    const payload = {
      question: 'Can a managing director be in the employment of the company?'
    };

    const res = await fetch(`${BASE_URL}/api/ask`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    const data = await res.json();
    if (res.status !== 200) {
      console.error('[Test Error] Received status:', res.status, 'Response payload:', JSON.stringify(data));
    }
    assert.strictEqual(res.status, 200, 'Endpoint should return HTTP 200');

    console.log('[Test Response Data]:', JSON.stringify(data, null, 2));
    assert.ok(data.answer, 'Response should contain an answer string');
    assert.ok(Array.isArray(data.searchResults), 'searchResults should be an array');
    assert.ok(data.searchResults.length > 0, 'Should have retrieved search results');

    const legislationSources = data.searchResults.filter(r => r.source_table === 'Legislation');
    const otherSources = data.searchResults.filter(r => r.source_table !== 'Legislation');

    console.log(`Retrieved search results breakdown: ${legislationSources.length} Legislation chunks + ${otherSources.length} Other chunks (Total: ${data.searchResults.length})`);
    
    assert.ok(legislationSources.length <= 4, 'Legislation sources should be at most 4');
    assert.ok(otherSources.length <= 5, 'Other sources should be at most 5');
    
    console.log('Sample answer generated by model:\n', data.answer.slice(0, 300) + '...');
  });
});
